# Generated by Django 4.2.2 on 2025-12-03 11:51

from django.db import migrations, models
import django.db.models.deletion
import learning.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0009_branch_abbreviation_branch_full_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccidentСategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Категория НС")),
            ],
            options={
                "verbose_name": "Категория НС",
                "verbose_name_plural": "Категории НС",
            },
        ),
        migrations.CreateModel(
            name="Accident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.CharField(
                        max_length=350, verbose_name="№ и дата информационного письма"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=learning.services.get_current_date,
                        verbose_name="Дата НС",
                    ),
                ),
                (
                    "contractor",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Подрядная организация",
                    ),
                ),
                (
                    "victims_count",
                    models.PositiveIntegerField(verbose_name="Количество пострадавших"),
                ),
                ("is_death", models.BooleanField(default=False, verbose_name="Смерть")),
                ("description", models.TextField(verbose_name="Описание НС")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="accident/photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accident",
                        to="accident.accidentсategory",
                        verbose_name="Категория НС",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accident",
                        to="organization.organization",
                        verbose_name="ОСТ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Несчастный случай",
                "verbose_name_plural": "Несчастные случаи",
                "ordering": ("-date",),
            },
        ),
    ]
