# Generated by Django 4.2.2 on 2025-12-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участок",
                "verbose_name_plural": "Участки",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group",
                        to="organization.district",
                        verbose_name="Участок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Краткое официальное название",
                        max_length=150,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Полное официальное название (если отличается от краткого)",
                        max_length=250,
                        verbose_name="Полное наименование",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="Сокращённое обозначение",
                        max_length=50,
                        verbose_name="Аббревиатура",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Признак основной ОСТ"
                    ),
                ),
            ],
            options={
                "verbose_name": "ОСТ",
                "verbose_name_plural": "ОСТы",
            },
        ),
        migrations.CreateModel(
            name="PositionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Наименование группы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа должностей",
                "verbose_name_plural": "Группы должностей",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organization/worker/",
                        verbose_name="Фотография работника",
                    ),
                ),
                (
                    "dismissed",
                    models.BooleanField(default=False, verbose_name="Уволен"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker",
                        to="organization.district",
                        verbose_name="Участок",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worker",
                        to="organization.group",
                        verbose_name="Группа участка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работник",
                "verbose_name_plural": "Работники",
            },
        ),
        migrations.CreateModel(
            name="StaffUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Сокращенное наименование должности (профессии)",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Полное наименование должности (профессии)",
                    ),
                ),
                (
                    "position_group",
                    models.ManyToManyField(
                        related_name="staffunit",
                        to="organization.positiongroup",
                        verbose_name="Группа работников",
                    ),
                ),
            ],
            options={
                "verbose_name": "Штатная единица",
                "verbose_name_plural": "Штатные единицы",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Основная профессия"
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position",
                        to="organization.staffunit",
                        verbose_name="Профессия/должность",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position",
                        to="organization.worker",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профессия/должность",
                "verbose_name_plural": "Профессии/должности",
                "ordering": ["is_main"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division",
                        to="organization.branch",
                        verbose_name="филиал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Структурное подразделение",
                "verbose_name_plural": "Структурные подразделения",
            },
        ),
        migrations.AddField(
            model_name="district",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="district",
                to="organization.division",
                verbose_name="Наименование структурного подразделения",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch",
                to="organization.organization",
                verbose_name="ОСТ",
            ),
        ),
    ]
