# Generated by Django 4.2.2 on 2025-12-08 20:07

from django.db import migrations, models
import django.db.models.deletion
import learning.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Направление обучения"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        verbose_name="Периодичность обучения в днях"
                    ),
                ),
                (
                    "have_sub_direction",
                    models.BooleanField(
                        default=False,
                        help_text="Только для 'В'",
                        verbose_name="Имеет поднаправления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление обучения",
                "verbose_name_plural": "Направления обучения",
            },
        ),
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "direction",
                    models.ManyToManyField(
                        related_name="learner",
                        to="learning.direction",
                        verbose_name="Направления обучения",
                    ),
                ),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner",
                        to="organization.position",
                        verbose_name="Должность/профессия",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner",
                        to="organization.worker",
                        verbose_name="Работник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обучаемый",
                "verbose_name_plural": "Обучаемые",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Наименование программы обучения"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        verbose_name="Продолжительность обучения (часов)"
                    ),
                ),
                (
                    "approve",
                    models.CharField(
                        help_text="Введите должность, И.О. Фамилию лица утвердившего программу",
                        max_length=150,
                        verbose_name="Программа утверждена",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        default=learning.services.get_current_date,
                        help_text="Введите дату в формате ДД.ММ.ГГГГ",
                        verbose_name="Дата утверждения программы",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Актуальность"),
                ),
                (
                    "doc_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=learning.services.add_doc_url,
                        verbose_name="Скан-копия программы обучения",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program",
                        to="organization.branch",
                        verbose_name="Филиал",
                    ),
                ),
                (
                    "direction",
                    models.ManyToManyField(
                        related_name="program",
                        to="learning.direction",
                        verbose_name="Направление обучения",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program",
                        to="organization.district",
                        verbose_name="Участок",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program",
                        to="organization.division",
                        verbose_name="Структурное подразделение",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program",
                        to="organization.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization",
                        to="organization.organization",
                        verbose_name="ОСТ",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program",
                        to="organization.position",
                        verbose_name="Наименование профессии",
                    ),
                ),
                (
                    "replacement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите программу, которую эта программа заменяет (не может быть самой собой)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replacement_for",
                        to="learning.program",
                        verbose_name="Замена программы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа обучения",
                "verbose_name_plural": "Программы обучения",
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prot_date",
                    models.DateField(
                        default=learning.services.get_current_date,
                        verbose_name="Дата протокола проверки знаний",
                    ),
                ),
                (
                    "doc_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=learning.services.add_prot_url,
                        verbose_name="Скан-копия протокола проверки знаний",
                    ),
                ),
                (
                    "chairman",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_chairman",
                        to="organization.worker",
                        verbose_name="Председатель комиссии",
                    ),
                ),
                (
                    "direction",
                    models.ManyToManyField(
                        related_name="protocol",
                        to="learning.direction",
                        verbose_name="Направление обучения",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol",
                        to="organization.division",
                        verbose_name="Структурное подразделение выдавшее протокол",
                    ),
                ),
                (
                    "learner",
                    models.ManyToManyField(
                        related_name="protocol",
                        to="learning.learner",
                        verbose_name="Работники проходящие проверку знаний",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="protocol_members",
                        to="organization.worker",
                        verbose_name="Члены комиссии",
                    ),
                ),
                (
                    "program",
                    models.ManyToManyField(
                        related_name="protocol",
                        to="learning.program",
                        verbose_name="Программа обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол проверки знаний",
                "verbose_name_plural": "Протоколы проверки знаний",
                "ordering": ["-prot_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250,
                        verbose_name="Направления обучения по программе В",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_direction",
                        to="learning.direction",
                        verbose_name="Направление обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поднаправление обучения для программы В",
                "verbose_name_plural": "Поднаправления обучения для программы В",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test",
                        to="learning.direction",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "sub_direction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Оставьте пустым, если тест для всего направления",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test",
                        to="learning.subdirection",
                        verbose_name="Поднаправление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.CreateModel(
            name="TestAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата назначения"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Назначен"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершён"),
                            ("expired", "Просрочен"),
                        ],
                        default="assigned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "attempts_left",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Осталось попыток"
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tests",
                        to="learning.learner",
                        verbose_name="Работник",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="learning.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение теста",
                "verbose_name_plural": "Назначения тестов",
            },
        ),
        migrations.CreateModel(
            name="StaffDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.ManyToManyField(
                        related_name="staff_direction",
                        to="learning.direction",
                        verbose_name="Направление обучения",
                    ),
                ),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_direction",
                        to="organization.staffunit",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор направлений обучения для профессии",
                "verbose_name_plural": "Наборы направлений обучения для профессий",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Вес вопроса (баллы)"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question",
                        to="learning.test",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="ProtocolResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passed", models.BooleanField(default=True, verbose_name="Сдал")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_result",
                        to="learning.learner",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_result",
                        to="learning.protocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат проверки знаний",
                "verbose_name_plural": "Результаты проверки знаний",
            },
        ),
        migrations.CreateModel(
            name="LearningPoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Наименование плаката"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="learning/learning_poster/",
                        verbose_name="Картинка плаката",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_poster",
                        to="learning.program",
                        verbose_name="Программа обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Плакат для обучения",
                "verbose_name_plural": "Плакаты для обучения",
            },
        ),
        migrations.CreateModel(
            name="LearningDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Наименование документа"
                    ),
                ),
                (
                    "doc",
                    models.FileField(
                        upload_to="learning/learning_doc/",
                        verbose_name="Файл документа",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_doc",
                        to="learning.program",
                        verbose_name="Программа обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ для обучения",
                "verbose_name_plural": "Документы для обучения",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kn_date",
                    models.DateField(
                        default=learning.services.get_current_date,
                        verbose_name="Дата проверки знаний",
                    ),
                ),
                (
                    "next_date",
                    models.DateField(
                        default=learning.services.get_current_date,
                        verbose_name="Дата следующей проверки знаний",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Актуальность"),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_date",
                        to="learning.direction",
                        verbose_name="Направление обучения",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_date",
                        to="learning.learner",
                        verbose_name="Работник",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_date",
                        to="learning.protocol",
                        verbose_name="Протокол проверки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дата проверки знаний",
                "verbose_name_plural": "Даты проверки знаний",
                "ordering": ["-kn_date"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст ответа")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="learning.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата тестирования"
                    ),
                ),
                ("is_passed", models.BooleanField(default=False, verbose_name="Сдан?")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Набранный балл (%)",
                    ),
                ),
                (
                    "total_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Максимально возможный балл"
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(default=1, verbose_name="Попытка №"),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="learning.learner",
                        verbose_name="Работник",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="learning.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат теста",
                "verbose_name_plural": "Результаты тестирования",
                "unique_together": {("test", "learner", "attempt_number")},
            },
        ),
        migrations.AddConstraint(
            model_name="test",
            constraint=models.UniqueConstraint(
                fields=("direction", "sub_direction"),
                name="unique_test_per_direction_or_subdirection",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="protocolresult",
            unique_together={("protocol", "learner")},
        ),
    ]
